name: Knockout
version: 1.0.0
author: Traunmagil

main: com.traunmagil.knockout.Main

api-version: 1.16

commands:
  deathnow:
    description: Kill yourself when in knockout mode
    permission: knockout.command.deathnow

permissions:
  knockout.command.deathnow:
    default: true
    description: Use /deathnow